# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'SynthAPI/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- script: |
    echo "Listing files in target directory:"
    dir "$(System.DefaultWorkingDirectory)/SynthAPI/target"
  displayName: 'Check target directory for JAR'


- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/SynthAPI/target'
    Contents: '*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- script: |
    echo "Listing files in artifact staging directory:"
    dir "$(build.artifactstagingdirectory)"
  displayName: 'Check artifact staging directory for JAR'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students (6b3f65f8-c627-4389-9b18-4e2623914819)'
    appType: 'webApp'
    WebAppName: 'SynthIA'
    package: '$(build.artifactstagingdirectory)/SynthAPI-0.0.1-SNAPSHOT.jar'
